[2023-06-19T05:39:53.194+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-06-19T05:39:53.214+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.csv_to_parquet scheduled__2023-06-19T04:00:00+00:00 [queued]>
[2023-06-19T05:39:53.230+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.csv_to_parquet scheduled__2023-06-19T04:00:00+00:00 [queued]>
[2023-06-19T05:39:53.230+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-06-19T05:39:53.253+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): csv_to_parquet> on 2023-06-19 04:00:00+00:00
[2023-06-19T05:39:53.262+0000] {standard_task_runner.py:57} INFO - Started process 237 to run task
[2023-06-19T05:39:53.268+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'csv_to_parquet', 'scheduled__2023-06-19T04:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_to_gcp.py', '--cfg-path', '/tmp/tmp0xf6c032']
[2023-06-19T05:39:53.272+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask csv_to_parquet
[2023-06-19T05:39:53.297+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-06-19T05:39:53.358+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion_gcs_dag.csv_to_parquet scheduled__2023-06-19T04:00:00+00:00 [running]> on host 0c6b91135793
[2023-06-19T05:39:53.377+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-06-19T05:39:53.752+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='csv_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2023-06-19T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-19T04:00:00+00:00'
[2023-06-19T05:39:53.758+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_data_to_gcp.py", line 60, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 1212, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1077, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1694, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1665, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 943, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 953, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 113, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/stock_data.csv'. Detail: [errno 2] No such file or directory
[2023-06-19T05:39:53.769+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=csv_to_parquet, execution_date=20230619T040000, start_date=20230619T053953, end_date=20230619T053953
[2023-06-19T05:39:53.785+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 4 for task csv_to_parquet ([Errno 2] Failed to open local file '/opt/airflow/stock_data.csv'. Detail: [errno 2] No such file or directory; 237)
[2023-06-19T05:39:53.840+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-19T05:39:53.889+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
